// data.js

export const employees = [
{
    id: 1,
    name: "Lanre Adeleye",
    title: "HR Manager",
    salary: 4200,
    phone: "040-1234567",
    email: "aino.virtanen@example.com",
    animal: "Owl",
    startDate: "2018-04-01",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"]
},
{
    id: 2,
    name: "Chinedu Okafor",
    title: "Software Engineer",
    salary: 250000,
    phone: "0803-123-4567",
    email: "okafor@net.com",
    animal: "Dog",
    startDate: "2020-02-10",
    location: "Lagos",
    department: "Engineering",
    skills: ["JavaScript", "React", "Node.js"]
},
{
    id: 3,
    name: "Aisha Bello",
    title: "Product Manager",
    salary: 300000,
    phone: "0802-456-7890",
    email: "bello@net.com",
    animal: "Bear",
    startDate: "2025-03-15",
    location: "Abuja",
    department: "Product",
    skills: ["Leadership", "Agile", "Figma"]
},
{
    id: 4,
    name: "Tunde Bakare",
    title: "Web Designer",
    salary: 220000,
    phone: "0812-987-6543",
    email: "bakare@net.com",
    animal: "Wolf",
    startDate: "2015-01-05",
    location: "Ibadan",
    department: "Design",
    skills: ["Figma", "HTML", "CSS"]
},
{
    id: 5,
    name: "Ngozi Umeh",
    title: "Software Developer",
    salary: 270000,
    phone: "0703-333-4444",
    email: "umeh@net.com",
    animal: "Cat",
    startDate: "2025-02-30",
    location: "Enugu",
    department: "Engineering",
    skills: ["Python", "Django", "REST APIs"]
},
{
    id: 6,
    name: "Babatunde Ajayi",
    title: "Product Owner",
    salary: 310000,
    phone: "0901-111-2222",
    email: "ajayi@net.com",
    animal: "Deer",
    startDate: "2017-10-12",
    location: "Kano",
    department: "Product",
    skills: ["Backlog Management", "Scrum", "CSS"]
},
{
    id: 7,
    name: "Funmi Adeyemi",
    title: "Software Architect",
    salary: 350000,
    phone: "0806-222-3333",
    email: "adeyemi@net.com",
    animal: "Dog",
    startDate: "2010-05-20",
    location: "Lagos",
    department: "Engineering",
    skills: ["Design", "Cloud", "DevOps"]
},
{
    id: 8,
    name: "Emeka Obi",
    title: "QA Engineer",
    salary: 200000,
    phone: "0810-444-5555",
    email: "obi@net.com",
    animal: "Fox",
    startDate: "2022-03-14",
    location: "Port Harcourt",
    department: "Quality Assurance",
    skills: ["Testing", "Automation", "HTML"]
},
{
    id: 9,
    name: "Hadiza Musa",
    title: "UI/UX Designer",
    salary: 230000,
    phone: "0807-111-3333",
    email: "musa@net.com",
    animal: "Rabbit",
    startDate: "2011-11-09",
    location: "Kaduna",
    department: "Design",
    skills: ["HTML", "CSS", "Prototyping"]
},
{
    id: 10,
    name: "Ifeanyi Eze",
    title: "DevOps Engineer",
    salary: 280000,
    phone: "0701-888-9999",
    email: "eze@net.com",
    animal: "Eagle",
    startDate: "2025-05-01",
    location: "Lagos",
    department: "Engineering",
    skills: ["CI/CD", "Docker", "Kubernetes"]
}
];
